---
- hosts: webservers
  become: yes
  vars_files:
    - "/home/lucky/ANSIBLE/Variable/vars.yaml"
#- [ "vars/{{ facter_operatingsystem }}.yml", "vars/defaults.yml" ] to call multiple file
  tasks:
  - name: name of package
    debug: 
      msg: "{{ name }}"

