---
- hosts: webservers
  vars: 
    Download: "/app"
    Destination: "/cops"
  tasks:
    - name: Delete files from /app
      shell: |
        cd "{{ Download }}"
        rm -rf *
      become: yes
    - name: Deploy Tar File
      maven_artifact:
        group_id: ant
        artifact_id: zipfile
        extension: zip
        repository_url: 'http://localhost:8081/repository/ant/'
        username: admin
        password: admin123
        mode: 0755
        owner: root
        group: root
        dest: "{{ Download }}"
      become: yes
    - name: unzip files
      shell: |
        find "{{ Download }}"  -name '*.zip' -exec sh -c 'unzip -jod `dirname {}` {}' ';'
      become: yes
    - name: copy content of /app into they /cops
      shell: |
        cd "{{ Download }}"
        rsync -av --exclude='*.zip' .  /cops
      become: yes
    - name: execute ant command
      shell: |
        cd "{{ Destination }}"
        ant clean
      become: yes
 
