---
- hosts: webservers
  tasks:
    - name: Deploy Tar File
      maven_artifact:
        group_id: sample
        artifact_id: tar
        extension: zip
        repository_url: 'http://localhost:8081/repository/mytar/'
        username: admin
        password: admin123
        mode: 0755
        owner: root
        group: root
        dest: /app/
      become: yes
    - name: get current date
      set_fact: bkpdate="{{ lookup('pipe', 'date +%Y.%m.%d.%H.%M.%S') }}"
    - name: Take the Backup of Downloaded Package
      shell: |
        cd /app/
        zip -Ru /bkp/{{ bkpdate }} '*.zip'
      become: yes  
    - name: unzip files
      shell: |
        find /app/ -name '*.zip' -exec sh -c 'unzip -od `dirname {}` {}' ';'
      become: yes
    - name: print message
      debug:
        msg: 'Delete Downloaded Package from /app/'
    - name: Delete Package
      shell: |
        find /app/ -name "*.zip" -exec rm -rf {} \;
      become: yes

